### ISSUE TITLE
Does this all run on arm as configured?

### ISSUE THREAD

**Issue by colek42** [ttyS0/kubernetes#1]

**Comment by ttyS0** [comment]
Not everything, no. I have a mixed architecture cluster, and I use `nodeSelector`s to specify `amd64` or `arm64` for images that can only run on a single architecture, whether that be because there isn't an `arm64` variant available or a multi-arch image isn't available . 

Presently I have four NUCs, two of which are K8s masters _and_ Ceph servers. A third NUC is a third K8s master, a third Ceph monitor, and a worker node. The forth NUC is only a worker node. Then I have five RPis (gen4 / 4GB) that are worker nodes, though only two are online at the moment as I'm prepping to move all my home lab gear to a different area of the house. 

Until recently I had the RPi nodes tainted with a `NoSchedule` since all my persistent storage is handled by Ceph, so there may be some other components that aren't `arm64` capable with some of the current configs that I just haven't noticed yet. 

Does that help?

**Comment by ttyS0** [comment]
@colek42 

I noticed your comment about `buildx`, switched to the `Edge` channel for Docker, and have started going through my containers and removing the `nodeSelector` where possible. There will be some that will never be run on `arm64`, `plex` for instance, but most of them do just fine.

Anyway, if there isn't anything else, can I close this?

**Comment by colek42** [comment]
Thanks!  This is a great resource as I get my lab setup.
